import { ContactBand, engineeringWhatsApp, PageHero, salesWhatsApp, SiteShell } from "../site-shell";

export const metadata = {title:"خدماتنا وخبراتنا | التصنيع الهندسي والتوريد",description:"خدمات تصميم وتصنيع وتطوير ودعم فني لدى الحسن للصناعات الهندسية، ومبيعات وعروض أسعار وتوريد عبر أسامة هيكل للتجارة والتوريدات."};

const engineeringServices=[["01","التصميم والتصنيع حسب الطلب","دراسة متطلبات المشروع وتطوير حلول ومعدات ملائمة للاستخدام المطلوب ضمن الإمكانات الفنية المتاحة."],["02","أعمال التصنيع الهندسي","أعمال القص والثني واللحام والتجميع وتصنيع الهياكل المعدنية للمعدات والحلول الزراعية والصناعية."],["03","التركيب والتشغيل والتدريب","المساعدة في التركيب والتشغيل الأولي والتدريب على الاستخدام الصحيح وإجراءات العناية الأساسية بالمعدات."],["04","الصيانة والدعم الفني","خدمات الصيانة والدعم الفني للمساعدة على استمرارية التشغيل وتلبية الاستفسارات المتعلقة بالمعدات."]];
const commercialServices=[["01","المبيعات وعروض الأسعار","استقبال طلبات المنتجات وإعداد عروض الأسعار وتوضيح نطاق التوريد التجاري."],["02","التوريد والعقود","تنسيق التوريد والعقود ومتابعة الطلبات حتى التسليم وفق الاتفاق التجاري."],["03","التنسيق التجاري","التواصل مع العملاء والمؤسسات والمنظمات وتنسيق متطلبات الكميات ومكان الاستخدام."],["04","خدمة العملاء","متابعة العميل وربطه بالقسم الهندسي عند الحاجة إلى مشورة فنية أو طلب تصنيع خاص."]];

export default function Services(){return <SiteShell><main>
  <PageHero eyebrow="خدماتنا وخبراتنا" title="مساران متكاملان من الهندسة إلى التوريد" copy="يتولى مصنع الحسن التصميم والتصنيع والدعم الفني، ويتولى أسامة هيكل المسار التجاري والمبيعات والتوريد والعقود وخدمة العملاء." />
  <section className="section service-axis engineering-axis"><div className="container"><div className="axis-heading"><img src="/al-hasan-logo.jpg" alt="شعار شركة الحسن للصناعات الهندسية" /><div><span className="eyebrow">المحور الأول</span><h2>التصنيع والحلول الهندسية</h2><p>شركة الحسن للصناعات الهندسية — الجهة المصنعة والمسؤولة عن الحلول الفنية.</p></div><a className="button primary" href={engineeringWhatsApp}>استفسار هندسي فني</a></div><div className="services-grid">{engineeringServices.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section service-axis commercial-axis"><div className="container"><div className="axis-heading"><img src="/osh-logo.jpg" alt="شعار أسامة هيكل للتجارة والتوريدات" /><div><span className="eyebrow">المحور الثاني</span><h2>التجارة والتوريد</h2><p>أسامة هيكل للتجارة والتوريدات — الشريك التجاري المسؤول عن رحلة البيع والتسليم.</p></div><a className="button primary" href={salesWhatsApp}>طلب عرض سعر</a></div><div className="services-grid">{commercialServices.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section experience"><div className="container experience-grid"><div><span className="eyebrow light">مجالات الخبرة</span><h2>خبرة متخصصة تدعم الزراعة والتجهيز</h2></div><ul><li>البذار والزراعة الحافظة</li><li>طحن وخلط وتجهيز الأعلاف</li><li>معالجة المخلفات الزراعية والأخشاب</li><li>الكبس والتغليف والنقل الزراعي</li><li>التركيب والتشغيل والتدريب والصيانة</li><li>المبيعات والتوريد والتنسيق التجاري</li></ul></div></section>
  <ContactBand />
</main></SiteShell>}
