import { engineeringWhatsApp, PageHero, salesWhatsApp, SiteShell } from "../site-shell";

export const metadata = {title:"تواصل معنا | المبيعات والهندسة والتصنيع",description:"تواصل مع أسامة هيكل للمبيعات والتوريد وعروض الأسعار، أو مع شركة الحسن وإسماعيل حورية للاستفسارات الهندسية والتصنيع."};

export default function Contact(){return <SiteShell><main>
  <PageHero eyebrow="تواصل معنا" title="اختر مسار التواصل المناسب" copy="لطلبات الأسعار والتوريد تواصل مع القسم التجاري، وللمواصفات والتصنيع والدعم الفني تواصل مباشرة مع مصنع الحسن." />
  <section className="section contact-page"><div className="container contact-paths">
    <article className="contact-path sales-path"><img src="/osh-logo.jpg" alt="شعار أسامة هيكل للتجارة والتوريدات" /><span className="eyebrow">المبيعات والتوريد</span><h2>أسامة هيكل للتجارة والتوريدات</h2><p>طلبات الأسعار، المبيعات، التوريد، العقود والاستفسارات التجارية.</p><dl><div><dt>الهاتف وWhatsApp</dt><dd><a href="tel:00963943990777" dir="ltr">00963 943 990 777</a></dd></div><div><dt>البريد الإلكتروني</dt><dd><a href="mailto:sales@osh-hassan.com" dir="ltr">sales@osh-hassan.com</a></dd></div></dl><a className="button quote-button" href={salesWhatsApp}>تواصل مع المبيعات عبر WhatsApp</a><a className="contact-email-link" href="mailto:sales@osh-hassan.com?subject=%D8%B7%D9%84%D8%A8%20%D8%B9%D8%B1%D8%B6%20%D8%B3%D8%B9%D8%B1">إرسال طلب عبر البريد الإلكتروني</a></article>
    <article className="contact-path engineering-path"><img src="/al-hasan-logo.jpg" alt="شعار شركة الحسن للصناعات الهندسية" /><span className="eyebrow">الاستفسارات الهندسية والتصنيع</span><h2>شركة الحسن للصناعات الهندسية</h2><p>المسؤول الفني: <b>إسماعيل حورية</b><br />الاستفسارات الفنية، مواصفات المعدات، التصنيع الخاص، تعديل المعدات والحلول الهندسية.</p><dl><div><dt>الهاتف وWhatsApp</dt><dd><a href="tel:00963937171347" dir="ltr">00963 937 171 347</a></dd></div><div><dt>البريد الإلكتروني</dt><dd><a href="mailto:engineering@osh-hassan.com" dir="ltr">engineering@osh-hassan.com</a></dd></div></dl><a className="button technical-button" href={engineeringWhatsApp}>تواصل مع المصنع عبر WhatsApp</a><a className="contact-email-link" href="mailto:engineering@osh-hassan.com?subject=%D8%A7%D8%B3%D8%AA%D9%81%D8%B3%D8%A7%D8%B1%20%D9%87%D9%86%D8%AF%D8%B3%D9%8A%20%D9%88%D9%81%D9%86%D9%8A">إرسال استفسار فني عبر البريد</a></article>
  </div><div className="container general-address"><span>العنوان العام</span><b>دمشق — سوريا</b><small>لا يجمع الموقع بيانات ولا يخزن رسائل؛ تُفتح وسيلة التواصل التي تختارها مباشرة.</small></div></section>
</main></SiteShell>}
