import { ContactBand, engineeringWhatsApp, PageHero, salesWhatsApp, SiteShell } from "../site-shell";
import { products } from "../site-data";

export const metadata = {title:"المنتجات والحلول | آلات زراعية وصناعية مصنعة لدى الحسن",description:"تسع آلات ومعدات زراعية وصناعية مصنعة مباشرة لدى شركة الحسن للصناعات الهندسية، مع عروض الأسعار والتوريد عبر أسامة هيكل للتجارة والتوريدات."};

export default function Products(){return <SiteShell><main>
  <PageHero eyebrow="المنتجات والحلول" title="معدات مصنعة للعمل الحقيقي" copy="جميع الآلات والمعدات المعروضة يتم تصنيعها مباشرة في ورش ومعامل شركة الحسن للصناعات الهندسية، بينما تُدار عروض الأسعار والمبيعات والتوريد عبر أسامة هيكل للتجارة والتوريدات." />
  <section className="manufacturing-notice"><div className="container"><img src="/al-hasan-logo.jpg" alt="شعار شركة الحسن للصناعات الهندسية" /><div><b>تصنيع مباشر لدى شركة الحسن للصناعات الهندسية</b><p>المواصفات المعروضة مستمدة حصراً من الملفات الفنية المعتمدة، ولم تتم إضافة أو تغيير أي قيمة فنية.</p></div></div></section>
  <section className="section product-list"><div className="container">{products.map((p,i)=><article className="product-row" id={`p-${p.code}`} key={p.code}><div className="product-image"><img src={p.image} alt={p.name} /><span>{p.code}</span></div><div className="product-body"><span className="eyebrow">حل زراعي وصناعي {String(i+1).padStart(2,"0")}</span><h2>{p.name}</h2><h3>{p.tagline}</h3><p>{p.description}</p><p className="manufacturer-line">مصنّع مباشرة بواسطة شركة الحسن للصناعات الهندسية.</p><div className="feature-chips">{p.features.map(f=><span key={f}>{f}</span>)}</div><details className="specs"><summary>عرض المواصفات الفنية <span>＋</span></summary><dl>{p.specs.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{p.note&&<p className="spec-note">ملاحظة: {p.note}</p>}</details><div className="product-contact-actions"><a className="button quote-button" href={salesWhatsApp}>طلب عرض سعر / توريد</a><a className="button technical-button" href={engineeringWhatsApp}>استفسار هندسي فني</a></div><div className="contact-route-note"><span>المبيعات والتوريد: أسامة هيكل</span><span>الهندسة والتصنيع: شركة الحسن — إسماعيل حورية</span></div></div></article>)}</div></section>
  <ContactBand />
</main></SiteShell>}
